export const modalDummy = {
    drink_name: "토닉워터",
    description: "진 토닉 칵테일에 쓰이는 칵테일 믹서로 레몬과 라임향의 상쾌한 맛과 고미성분의 쌉쌀한 맛을 낸다.",
    calorie: 145,
    manufacture: "롯데칠성",
    price: 1400,
    large_category: "논알콜",
    medium_category: "탄산",
    small_category: "사이다",
    img: "",
    alcohol: 0,
    measure: 330,
    caffeine: 0,
    tag: null,
    like_cnt: 0,
};
