export const dummy = {
    results: [
        {
            animal_idx: 1,
            imgUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Border_Collie_panting.jpg/800px-Border_Collie_panting.jpg",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
    ],
};
